export const CREATE_DATA = 'CREATE_DATA'

export const PUSH_ITEMS_BASKET = 'PUSH_ITEMS_BASKET'
export const DELETE_ITEM_BASKET = 'DELETE_ITEM_BASKET'

export const PUSH_CATEGORY = 'PUSH_CATEGORY'
export const PUSH_SUB_CATEGORY = 'PUSH_SUB_CATEGORY'

export const PUSH_COLLECTIONS = 'PUSH_COLLECTIONS'
export const PUSH_ONE_COLLECTION = 'PUSH_ONE_COLLECTION'
export const PUSH_NEWS_COLLECTIONS = 'PUSH_NEWS_COLLECTIONS'
export const PUSH_HIT_COLLECTIONS = 'PUSH_HIT_COLLECTIONS'
export const PUSH_OTHER_COLLECTIONS = 'PUSH_OTHER_COLLECTIONS'
export const PUSH_ITEMS_SLIDER_COLLECTIONS = 'PUSH_ITEMS_SLIDER_COLLECTIONS'
