export const CREATE_DATA = "CREATE_DATA";

export const PUSH_ITEMS_BASKET = "PUSH_ITEMS_BASKET";
export const DELETE_ITEM_BASKET = "DELETE_ITEM_BASKET";

export const PUSH_CATEGORY = "PUSH_CATEGORY";
export const PUSH_SUB_CATEGORY = "PUSH_SUB_CATEGORY";

export const PUSH_COLLECTIONS = "PUSH_COLLECTIONS";
export const PUSH_ONE_COLLECTION = "PUSH_ONE_COLLECTION";
export const PUSH_ALL_COLLECTIONS = "PUSH_ALL_COLLECTIONS";
export const PUSH_NEWS_COLLECTIONS = "PUSH_NEWS_COLLECTIONS";
export const PUSH_HIT_COLLECTIONS = "PUSH_HIT_COLLECTIONS";
export const PUSH_OTHER_COLLECTIONS = "PUSH_OTHER_COLLECTIONS";
export const PUSH_ITEMS_SLIDER_COLLECTIONS = "PUSH_ITEMS_SLIDER_COLLECTIONS";
export const PLUS_ITEMS_PRICE = "PLUS_ITEMS_PRICE";
export const PUSH_ITEMS_TO_SALE = "PUSH_ITEMS_TO_SALE";
export const SET_TOTAL_PRICE = "SET_TOTAL_PRICE";

export const SET_FILTERS_TO_STORE = "SET_FILTERS_TO_STORE";
export const RE_SET_FILTERS = "RE_SET_FITLERS"
export const CHECK_SIZE_FILTER = "CHECK_SIZE_FILTER"
export const CHECK_SURFACE_FILTER = "CHECK_SURFACE_FILTER"
export const CHECK_USAGE_FILTER = "CHECK_USAGE_FILTER"
export const SET_LOADING_FILTER = "SET_LOADING_FILTER"